sm6150_au: Add default BroadcastRadio HAL
Add default broadcastradio service to fix following runtime errors.
E AndroidRuntime: java.lang.RuntimeException:
Unable to create service com.android.car.radio.service.RadioAppService:
java.lang.NullPointerException: RadioManager could not be loaded

Change-Id: I4369df78ca5c37f2a50afc246e78de6b08b8bffc
Signed-off-by: Sindhu Kanathur <quic_skanathu@quicinc.com>
(cherry picked from commit cc0b27564414e0c3c50c189632d833d77cc54653)